In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./M3_Data.csv")
df.head()

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198

In [3]:
df.shape

(41, 4)

# Question 1

Write a Python/NumPy code block that finds the distinct array items that exist in either array a or array b but which do not appear within both arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
For example, if a 2 is found in both array a and array b, your output should not include a 2. Furthermore, the content of the output should be comprised solely of unique data values.

In [4]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [5]:
# Use the union1d method to find the unique elements in either array a or array b
unique_elements = np.union1d(a, b)

# Use the in1d method to find the elements that exist in both arrays
duplicate_elements = np.intersect1d(a, b)

# Use the setdiff1d method to find the unique elements in unique_elements that are not in duplicate_elements
result1 = np.setdiff1d(unique_elements, duplicate_elements)

print(result1)

[ 1  3  5  6  7  8  9 10]


# Questions 2

In [6]:
# set array from 1,2,3,4 and reshape as vertical array. 
start = np.arange(1,5).reshape(4, 1)
# start stores in result2
result2 = start
# make each vertical array and stack 
for i in range(1, 5):
    result2 = np.hstack((result2, start + 4 * i))
    
result2

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

- First, reshape the [1, 2, 3, 4] array vertically to the start array. Then, after creating an empty array called result2, start array + 4 * i arrays are stacked one by one.

# Quetions 3

In [7]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])

c = np.setdiff1d(b, a)
a = np.concatenate((a, c))

a

array([12,  5,  7, 15,  3,  1,  8,  4,  6, 11, 14, 19])

- can use the Numpy library's Setdiff1d function to get the items in b that are not in a, and then use Numpy's Concatenate function to add these items to a:

# Question 4

In [8]:
flattened_array = result2.ravel()
flattened_array

array([ 1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7, 11, 15, 19,  4,  8,
       12, 16, 20])

- can use the Numpy library's Ravel function to flatten the array

# Question 5